services:
  aeropuerto-server:
    image: aeropuerto-api:latest
    container_name: aeropuerto-api
    build:
      context: .
      dockerfile: DockerFile
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5000,server=y,suspend=n
    ports:
      - "8080:8080"
      - "5000:5000"
networks:
  default:
    external: true
    name: aeropuerto-net
