version: '3.8'
services:
  redis-server:
    container_name: aeropuertoRedisDB
    image: 'redis:8.0.1-alpine'
    ports:
      - "6379:6379"

networks:
  default:
    external: true
    name: aeropuerto-net